
# file: ibert_ultrascale_gth_0.xdc
####################################################################################
##   ____  ____ 
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 2012.3
##  \   \         Application : IBERT Ultrascale
##  /   /         Filename : example_ibert_ultrascale_gth_0.xdc
## /___/   /\     
## \   \  /  \ 
##  \___\/\___\
##
##
## 
## Generated by Xilinx IBERT 7Series 
##**************************************************************************
##
## Icon Constraints
##
set_property C_CLK_INPUT_FREQ_HZ 156250000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER true [get_debug_cores dbg_hub]

##gth_refclk lock constraints
##
set_property PACKAGE_PIN V6 [get_ports gth_refclk0p_i[0]]
set_property PACKAGE_PIN V5 [get_ports gth_refclk0n_i[0]]
set_property PACKAGE_PIN T6 [get_ports gth_refclk1p_i[0]]
set_property PACKAGE_PIN T5 [get_ports gth_refclk1n_i[0]]
##
## Refclk constraints
##
create_clock -name gth_refclk0_7 -period 6.4 [get_ports gth_refclk0p_i[0]]
create_clock -name gth_refclk1_7 -period 6.4 [get_ports gth_refclk1p_i[0]]
set_clock_groups -group [get_clocks gth_refclk0_7 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gth_refclk1_7 -include_generated_clocks] -asynchronous


## ===== FMC_4SFP control signals, VERSION A (verified vs guide 2026-08-27) =====
set_property -dict {PACKAGE_PIN H26  IOSTANDARD LVCMOS33} [get_ports {sfp_tx_disable[0]}]
set_property -dict {PACKAGE_PIN AH12 IOSTANDARD LVCMOS33} [get_ports {sfp_tx_disable[1]}]
set_property -dict {PACKAGE_PIN J25  IOSTANDARD LVCMOS33} [get_ports {sfp_tx_disable[2]}]
set_property -dict {PACKAGE_PIN AF12 IOSTANDARD LVCMOS33} [get_ports {sfp_tx_disable[3]}]
set_property -dict {PACKAGE_PIN G27  IOSTANDARD LVCMOS33} [get_ports {sfp_rs0[0]}]
set_property -dict {PACKAGE_PIN AH11 IOSTANDARD LVCMOS33} [get_ports {sfp_rs0[1]}]
set_property -dict {PACKAGE_PIN M26  IOSTANDARD LVCMOS33} [get_ports {sfp_rs0[2]}]
set_property -dict {PACKAGE_PIN AF13 IOSTANDARD LVCMOS33} [get_ports {sfp_rs0[3]}]
set_property -dict {PACKAGE_PIN H27  IOSTANDARD LVCMOS33} [get_ports {sfp_rs1[0]}]
set_property -dict {PACKAGE_PIN AG11 IOSTANDARD LVCMOS33} [get_ports {sfp_rs1[1]}]
set_property -dict {PACKAGE_PIN M25  IOSTANDARD LVCMOS33} [get_ports {sfp_rs1[2]}]
set_property -dict {PACKAGE_PIN AE13 IOSTANDARD LVCMOS33} [get_ports {sfp_rs1[3]}]