

create_clock -period 8.000 -name eth_rxc [get_ports eth_rxc]


set_property PACKAGE_PIN AC34 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS18 [get_ports sys_rst_n]
set_property PACKAGE_PIN AA33 [get_ports eth_rst_n]
set_property PACKAGE_PIN Y33 [get_ports eth_rx_ctl]
set_property PACKAGE_PIN AC31 [get_ports eth_rxc]
set_property PACKAGE_PIN AE32 [get_ports eth_tx_ctl]
set_property PACKAGE_PIN Y32 [get_ports eth_txc]
set_property PACKAGE_PIN AC32 [get_ports {eth_rxd[3]}]
set_property PACKAGE_PIN V33 [get_ports {eth_rxd[2]}]
set_property PACKAGE_PIN W34 [get_ports {eth_rxd[1]}]
set_property PACKAGE_PIN W33 [get_ports {eth_rxd[0]}]
set_property PACKAGE_PIN AG30 [get_ports {eth_txd[3]}]
set_property PACKAGE_PIN AF30 [get_ports {eth_txd[2]}]
set_property PACKAGE_PIN AF32 [get_ports {eth_txd[1]}]
set_property PACKAGE_PIN Y31 [get_ports {eth_txd[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports eth_rxc]
set_property IOSTANDARD LVCMOS18 [get_ports eth_txc]
set_property IOSTANDARD LVCMOS18 [get_ports eth_rst_n]
set_property IOSTANDARD LVCMOS18 [get_ports eth_rx_ctl]
set_property IOSTANDARD LVCMOS18 [get_ports eth_tx_ctl]
set_property IOSTANDARD LVCMOS18 [get_ports {eth_txd[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {eth_txd[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {eth_txd[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {eth_txd[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {eth_rxd[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {eth_rxd[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {eth_rxd[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {eth_rxd[0]}]
set_property PACKAGE_PIN Y30 [get_ports key]
set_property IOSTANDARD LVCMOS18 [get_ports key]

set_property BITSTREAM.CONFIG.UNUSEDPIN PULLNONE [current_design]
