#开发板IO约束文件

#----------------------系统时钟---------------------------
#时钟周期约束
#create_clock -period 10.000 -name sys_clk_p [get_ports sys_clk_p]
create_clock -period 10.000 -name sys_clk_p [get_ports diff_clock_rtl_0_clk_p]
#时钟管脚
#set_property PACKAGE_PIN AK17 [get_ports sys_clk_p]
#set_property IOSTANDARD DIFF_HSTL_I_12 [get_ports sys_clk_p]
#set_property IOSTANDARD DIFF_HSTL_I_12 [get_ports sys_clk_n]
set_property PACKAGE_PIN AK17 [get_ports diff_clock_rtl_0_clk_p]
set_property IOSTANDARD DIFF_HSTL_I_12 [get_ports diff_clock_rtl_0_clk_p]
set_property IOSTANDARD DIFF_HSTL_I_12 [get_ports diff_clock_rtl_0_clk_n]

#----------------------系统复位---------------------------
#set_property -dict {PACKAGE_PIN AC34 IOSTANDARD LVCMOS18} [get_ports sys_rst_n]
set_property -dict {PACKAGE_PIN AC34 IOSTANDARD LVCMOS18} [get_ports reset_rtl_0]
#----------------------KEY---------------------------
set_property -dict {PACKAGE_PIN Y30 IOSTANDARD LVCMOS18} [get_ports key[0]]
set_property -dict {PACKAGE_PIN W30 IOSTANDARD LVCMOS18} [get_ports key[1]]

#----------------------LED---------------------------
set_property -dict {PACKAGE_PIN T22 IOSTANDARD LVCMOS18} [get_ports {led[0]}]
set_property -dict {PACKAGE_PIN T23 IOSTANDARD LVCMOS18} [get_ports {led[1]}]

#----------------------UART---------------------------
set_property -dict {PACKAGE_PIN AE33 IOSTANDARD LVCMOS18} [get_ports uart_rxd]
set_property -dict {PACKAGE_PIN AF34 IOSTANDARD LVCMOS18} [get_ports uart_txd]

#set_property -dict {PACKAGE_PIN AE33 IOSTANDARD LVCMOS18} [get_ports uart_rtl_0_rxd]
#set_property -dict {PACKAGE_PIN AF34 IOSTANDARD LVCMOS18} [get_ports uart_rtl_0_txd]
#----------------------IIC（EEPROM）----------------------
set_property -dict {PACKAGE_PIN AM12 IOSTANDARD LVCMOS33} [get_ports iic_scl]
set_property -dict {PACKAGE_PIN AN12 IOSTANDARD LVCMOS33} [get_ports iic_sda]

#----------------------LVDS接口----------------------------
set_property -dict {PACKAGE_PIN D20 IOSTANDARD LVDS} [get_ports {tx_out_p[0]}]
set_property -dict {PACKAGE_PIN D23 IOSTANDARD LVDS} [get_ports {tx_out_p[1]}]
set_property -dict {PACKAGE_PIN H21 IOSTANDARD LVDS} [get_ports {tx_out_p[2]}]
set_property -dict {PACKAGE_PIN G22 IOSTANDARD LVDS} [get_ports {tx_out_p[3]}]
set_property -dict {PACKAGE_PIN D21 IOSTANDARD LVDS} [get_ports {tx_out_n[0]}]
set_property -dict {PACKAGE_PIN C23 IOSTANDARD LVDS} [get_ports {tx_out_n[1]}]
set_property -dict {PACKAGE_PIN G21 IOSTANDARD LVDS} [get_ports {tx_out_n[2]}]
set_property -dict {PACKAGE_PIN F22 IOSTANDARD LVDS} [get_ports {tx_out_n[3]}]
set_property -dict {PACKAGE_PIN G20 IOSTANDARD LVDS} [get_ports tx_clk_p]
set_property -dict {PACKAGE_PIN F20 IOSTANDARD LVDS} [get_ports tx_clk_n]
set_property -dict {PACKAGE_PIN H22 IOSTANDARD LVCMOS18} [get_ports video_bl]

#----------------------HDMI输入接口----------------------------
set_property PACKAGE_PIN AP11 [get_ports iic_scl]
set_property PACKAGE_PIN AP10 [get_ports iic_sda]
set_property PACKAGE_PIN AL10 [get_ports rstn_out]
set_property IOSTANDARD LVCMOS33 [get_ports iic_scl]
set_property IOSTANDARD LVCMOS33 [get_ports iic_sda]
set_property IOSTANDARD LVCMOS33 [get_ports rstn_out]

set_property PACKAGE_PIN AF9 [get_ports video_clk_in]
set_property PACKAGE_PIN AD9 [get_ports video_de_in]
set_property PACKAGE_PIN AE10 [get_ports video_hs_in]
set_property PACKAGE_PIN AD10 [get_ports video_vs_in]
set_property IOSTANDARD LVCMOS33 [get_ports video_clk_in]
set_property IOSTANDARD LVCMOS33 [get_ports video_de_in]
set_property IOSTANDARD LVCMOS33 [get_ports video_hs_in]
set_property IOSTANDARD LVCMOS33 [get_ports video_vs_in]

set_property PACKAGE_PIN AD8 [get_ports {video_rgb_in[0]}]
set_property PACKAGE_PIN AF8 [get_ports {video_rgb_in[1]}]
set_property PACKAGE_PIN AE8 [get_ports {video_rgb_in[2]}]
set_property PACKAGE_PIN AH13 [get_ports {video_rgb_in[3]}]
set_property PACKAGE_PIN AH9 [get_ports {video_rgb_in[4]}]
set_property PACKAGE_PIN AH8 [get_ports {video_rgb_in[5]}]
set_property PACKAGE_PIN AE11 [get_ports {video_rgb_in[6]}]
set_property PACKAGE_PIN AD11 [get_ports {video_rgb_in[7]}]
set_property PACKAGE_PIN AJ13 [get_ports {video_rgb_in[8]}]
set_property PACKAGE_PIN AM11 [get_ports {video_rgb_in[9]}]
set_property PACKAGE_PIN AL12 [get_ports {video_rgb_in[10]}]
set_property PACKAGE_PIN AN11 [get_ports {video_rgb_in[11]}]
set_property PACKAGE_PIN AK12 [get_ports {video_rgb_in[12]}]
set_property PACKAGE_PIN AN9 [get_ports {video_rgb_in[13]}]
set_property PACKAGE_PIN AM10 [get_ports {video_rgb_in[14]}]
set_property PACKAGE_PIN AP9 [get_ports {video_rgb_in[15]}]
set_property PACKAGE_PIN AG9 [get_ports {video_rgb_in[16]}]
set_property PACKAGE_PIN AK8 [get_ports {video_rgb_in[17]}]
set_property PACKAGE_PIN AJ8 [get_ports {video_rgb_in[18]}]
set_property PACKAGE_PIN AJ9 [get_ports {video_rgb_in[19]}]
set_property PACKAGE_PIN AG10 [get_ports {video_rgb_in[20]}]
set_property PACKAGE_PIN AK10 [get_ports {video_rgb_in[21]}]
set_property PACKAGE_PIN AL8 [get_ports {video_rgb_in[22]}]
set_property PACKAGE_PIN AP8 [get_ports {video_rgb_in[23]}]

set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[0]}]

#------------------HDMI输出接口----------------------
set_property PACKAGE_PIN AP11 [get_ports iic_scl]
set_property PACKAGE_PIN AP10 [get_ports iic_sda]
set_property PACKAGE_PIN AL10 [get_ports rstn_out]
set_property IOSTANDARD LVCMOS33 [get_ports iic_scl]
set_property IOSTANDARD LVCMOS33 [get_ports iic_sda]
set_property IOSTANDARD LVCMOS33 [get_ports rstn_out]

set_property PACKAGE_PIN P24 [get_ports video_clk_out]
set_property PACKAGE_PIN T24 [get_ports video_de_out]
set_property PACKAGE_PIN T27 [get_ports video_hs_out]
set_property PACKAGE_PIN T25 [get_ports video_vs_out]
set_property PACKAGE_PIN R27 [get_ports {video_rgb_out[0]}]
set_property PACKAGE_PIN R26 [get_ports {video_rgb_out[1]}]
set_property PACKAGE_PIN K21 [get_ports {video_rgb_out[2]}]
set_property PACKAGE_PIN R25 [get_ports {video_rgb_out[3]}]
set_property PACKAGE_PIN K20 [get_ports {video_rgb_out[4]}]
set_property PACKAGE_PIN P21 [get_ports {video_rgb_out[5]}]
set_property PACKAGE_PIN P20 [get_ports {video_rgb_out[6]}]
set_property PACKAGE_PIN P23 [get_ports {video_rgb_out[7]}]
set_property PACKAGE_PIN R23 [get_ports {video_rgb_out[8]}]
set_property PACKAGE_PIN K26 [get_ports {video_rgb_out[9]}]
set_property PACKAGE_PIN N22 [get_ports {video_rgb_out[10]}]
set_property PACKAGE_PIN N21 [get_ports {video_rgb_out[11]}]
set_property PACKAGE_PIN L23 [get_ports {video_rgb_out[12]}]
set_property PACKAGE_PIN L24 [get_ports {video_rgb_out[13]}]
set_property PACKAGE_PIN L27 [get_ports {video_rgb_out[14]}]
set_property PACKAGE_PIN M27 [get_ports {video_rgb_out[15]}]
set_property PACKAGE_PIN K25 [get_ports {video_rgb_out[16]}]
set_property PACKAGE_PIN M21 [get_ports {video_rgb_out[17]}]
set_property PACKAGE_PIN H24 [get_ports {video_rgb_out[18]}]
set_property PACKAGE_PIN J23 [get_ports {video_rgb_out[19]}]
set_property PACKAGE_PIN L22 [get_ports {video_rgb_out[20]}]
set_property PACKAGE_PIN M22 [get_ports {video_rgb_out[21]}]
set_property PACKAGE_PIN K23 [get_ports {video_rgb_out[22]}]
set_property PACKAGE_PIN K27 [get_ports {video_rgb_out[23]}]

set_property IOSTANDARD LVCMOS33 [get_ports video_clk_out]
set_property IOSTANDARD LVCMOS33 [get_ports video_de_out]
set_property IOSTANDARD LVCMOS33 [get_ports video_hs_out]
set_property IOSTANDARD LVCMOS33 [get_ports video_vs_out]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[0]}]

#--------------------摄像头接口------------------------
create_clock -period 40.000 -name cmos_pclk [get_ports cam_pclk]
#ov5640
set_property PACKAGE_PIN W23 [get_ports cam_pclk]
set_property PACKAGE_PIN U24 [get_ports {cam_data[7]}]
set_property PACKAGE_PIN U25 [get_ports {cam_data[6]}]
set_property PACKAGE_PIN U21 [get_ports {cam_data[5]}]
set_property PACKAGE_PIN U22 [get_ports {cam_data[4]}]
set_property PACKAGE_PIN V23 [get_ports {cam_data[3]}]
set_property PACKAGE_PIN V22 [get_ports {cam_data[2]}]
set_property PACKAGE_PIN V21 [get_ports {cam_data[1]}]
set_property PACKAGE_PIN W21 [get_ports {cam_data[0]}]
set_property PACKAGE_PIN Y21 [get_ports cam_href]
set_property PACKAGE_PIN W24 [get_ports cam_pwdn]
set_property PACKAGE_PIN AE27 [get_ports cam_rst_n]
set_property PACKAGE_PIN AN13 [get_ports cam_scl]
set_property PACKAGE_PIN AP13 [get_ports cam_sda]
set_property PACKAGE_PIN Y22 [get_ports cam_vsync]
set_property IOSTANDARD LVCMOS18 [get_ports cam_pclk]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_data[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_data[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_data[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_data[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_data[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_data[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_data[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_data[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports cam_href]
set_property IOSTANDARD LVCMOS18 [get_ports cam_pwdn]
set_property IOSTANDARD LVCMOS18 [get_ports cam_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports cam_scl]
set_property IOSTANDARD LVCMOS33 [get_ports cam_sda]
set_property IOSTANDARD LVCMOS18 [get_ports cam_vsync]

#ov7725
set_property PACKAGE_PIN W23 [get_ports cam_pclk]
set_property PACKAGE_PIN U24 [get_ports {cam_data[7]}]
set_property PACKAGE_PIN U25 [get_ports {cam_data[6]}]
set_property PACKAGE_PIN U21 [get_ports {cam_data[5]}]
set_property PACKAGE_PIN U22 [get_ports {cam_data[4]}]
set_property PACKAGE_PIN V23 [get_ports {cam_data[3]}]
set_property PACKAGE_PIN V22 [get_ports {cam_data[2]}]
set_property PACKAGE_PIN V21 [get_ports {cam_data[1]}]
set_property PACKAGE_PIN W21 [get_ports {cam_data[0]}]
set_property PACKAGE_PIN Y21 [get_ports cam_href]
set_property PACKAGE_PIN W24 [get_ports cam_sgm_ctrl]
set_property PACKAGE_PIN AE27 [get_ports cam_rst_n]
set_property PACKAGE_PIN AN13 [get_ports cam_scl]
set_property PACKAGE_PIN AP13 [get_ports cam_sda]
set_property IOSTANDARD LVCMOS18 [get_ports cam_pclk]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_data[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_data[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_data[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_data[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_data[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_data[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_data[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_data[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports cam_href]
set_property IOSTANDARD LVCMOS18 [get_ports cam_sgm_ctrl]
set_property IOSTANDARD LVCMOS18 [get_ports cam_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports cam_scl]
set_property IOSTANDARD LVCMOS33 [get_ports cam_sda]
set_property PACKAGE_PIN Y22 [get_ports cam_vsync]
set_property IOSTANDARD LVCMOS18 [get_ports cam_vsync]


#----------------------以太网---------------------------
create_clock -period 8.000 -name eth_rxc [get_ports eth_rxc]
#GE1
set_property -dict {PACKAGE_PIN AD30 IOSTANDARD LVCMOS18} [get_ports eth_rxc]
set_property -dict {PACKAGE_PIN V32 IOSTANDARD LVCMOS18} [get_ports eth_rst_n]
set_property -dict {PACKAGE_PIN V34 IOSTANDARD LVCMOS18} [get_ports eth_rx_ctl]
set_property -dict {PACKAGE_PIN U34 IOSTANDARD LVCMOS18} [get_ports {eth_rxd[0]}]
set_property -dict {PACKAGE_PIN AD33 IOSTANDARD LVCMOS18} [get_ports {eth_rxd[1]}]
set_property -dict {PACKAGE_PIN AC33 IOSTANDARD LVCMOS18} [get_ports {eth_rxd[2]}]
set_property -dict {PACKAGE_PIN AD31 IOSTANDARD LVCMOS18} [get_ports {eth_rxd[3]}]
set_property -dict {PACKAGE_PIN AF28 IOSTANDARD LVCMOS18} [get_ports eth_txc]
set_property -dict {PACKAGE_PIN AD28 IOSTANDARD LVCMOS18} [get_ports eth_tx_ctl]
set_property -dict {PACKAGE_PIN AE28 IOSTANDARD LVCMOS18} [get_ports {eth_txd[0]}]
set_property -dict {PACKAGE_PIN AC28 IOSTANDARD LVCMOS18} [get_ports {eth_txd[1]}]
set_property -dict {PACKAGE_PIN AD29 IOSTANDARD LVCMOS18} [get_ports {eth_txd[2]}]
set_property -dict {PACKAGE_PIN AE30 IOSTANDARD LVCMOS18} [get_ports {eth_txd[3]}]

#GE2
set_property -dict {PACKAGE_PIN AC31 IOSTANDARD LVCMOS18} [get_ports eth_rxc]
set_property -dict {PACKAGE_PIN AA33 IOSTANDARD LVCMOS18} [get_ports eth_rst_n]
set_property -dict {PACKAGE_PIN Y33 IOSTANDARD LVCMOS18} [get_ports eth_rx_ctl]
set_property -dict {PACKAGE_PIN W33 IOSTANDARD LVCMOS18} [get_ports {eth_rxd[0]}]
set_property -dict {PACKAGE_PIN W34 IOSTANDARD LVCMOS18} [get_ports {eth_rxd[1]}]
set_property -dict {PACKAGE_PIN V33 IOSTANDARD LVCMOS18} [get_ports {eth_rxd[2]}]
set_property -dict {PACKAGE_PIN AC32 IOSTANDARD LVCMOS18} [get_ports {eth_rxd[3]}]
set_property -dict {PACKAGE_PIN Y32 IOSTANDARD LVCMOS18} [get_ports eth_txc]
set_property -dict {PACKAGE_PIN AE32 IOSTANDARD LVCMOS18} [get_ports eth_tx_ctl]
set_property -dict {PACKAGE_PIN Y31 IOSTANDARD LVCMOS18} [get_ports {eth_txd[0]}]
set_property -dict {PACKAGE_PIN AF32 IOSTANDARD LVCMOS18} [get_ports {eth_txd[1]}]
set_property -dict {PACKAGE_PIN AF30 IOSTANDARD LVCMOS18} [get_ports {eth_txd[2]}]
set_property -dict {PACKAGE_PIN AG30 IOSTANDARD LVCMOS18} [get_ports {eth_txd[3]}]

#----------------------SD卡---------------------------
set_property PACKAGE_PIN A12 [get_ports sd_clk]
set_property IOSTANDARD LVCMOS18 [get_ports sd_clk]
set_property PACKAGE_PIN B11 [get_ports sd_cs]
set_property IOSTANDARD LVCMOS18 [get_ports sd_cs]
set_property PACKAGE_PIN A13 [get_ports sd_miso]
set_property IOSTANDARD LVCMOS18 [get_ports sd_miso]
set_property PACKAGE_PIN C13 [get_ports sd_mosi]
set_property IOSTANDARD LVCMOS18 [get_ports sd_mosi]

#----------------------FLASH---------------------------
set_property PACKAGE_PIN G26 [get_ports spi_cs]
set_property IOSTANDARD LVCMOS33 [get_ports spi_cs]
set_property PACKAGE_PIN M20 [get_ports spi_mosi]
set_property IOSTANDARD LVCMOS33 [get_ports spi_miso]
set_property IOSTANDARD LVCMOS33 [get_ports spi_mosi]
set_property PACKAGE_PIN L20 [get_ports spi_miso]

#----------------------RS485---------------------------
#rs485 1
set_property -dict {PACKAGE_PIN AA34 IOSTANDARD LVCMOS18} [get_ports rs485_uart_rxd]
set_property -dict {PACKAGE_PIN AB34 IOSTANDARD LVCMOS18} [get_ports rs485_uart_txd]
#rs485 2
set_property -dict {PACKAGE_PIN AG31 IOSTANDARD LVCMOS18} [get_ports rs485_uart_rxd]
set_property -dict {PACKAGE_PIN AG32 IOSTANDARD LVCMOS18} [get_ports rs485_uart_txd]

#----------------------CAN---------------------------
#CAN 1
set_property -dict {PACKAGE_PIN AB32 IOSTANDARD LVCMOS18} [get_ports rs485_uart_rxd]
set_property -dict {PACKAGE_PIN AA32 IOSTANDARD LVCMOS18} [get_ports rs485_uart_txd]
#CAN 2
set_property -dict {PACKAGE_PIN AG29 IOSTANDARD LVCMOS18} [get_ports rs485_uart_rxd]
set_property -dict {PACKAGE_PIN AF29 IOSTANDARD LVCMOS18} [get_ports rs485_uart_txd]

#----------------------DDR4---------------------------
#DDR4
set_property PACKAGE_PIN AG14 [get_ports {c0_ddr4_adr[0]}]
set_property PACKAGE_PIN AF17 [get_ports {c0_ddr4_adr[1]}]
set_property PACKAGE_PIN AF15 [get_ports {c0_ddr4_adr[2]}]
set_property PACKAGE_PIN AJ14 [get_ports {c0_ddr4_adr[3]}]
set_property PACKAGE_PIN AD18 [get_ports {c0_ddr4_adr[4]}]
set_property PACKAGE_PIN AG17 [get_ports {c0_ddr4_adr[5]}]
set_property PACKAGE_PIN AE17 [get_ports {c0_ddr4_adr[6]}]
set_property PACKAGE_PIN AK18 [get_ports {c0_ddr4_adr[7]}]
set_property PACKAGE_PIN AD16 [get_ports {c0_ddr4_adr[8]}]
set_property PACKAGE_PIN AH18 [get_ports {c0_ddr4_adr[9]}]
set_property PACKAGE_PIN AD19 [get_ports {c0_ddr4_adr[10]}]
set_property PACKAGE_PIN AD15 [get_ports {c0_ddr4_adr[11]}]
set_property PACKAGE_PIN AL17 [get_ports {c0_ddr4_adr[13]}]
set_property PACKAGE_PIN AH16 [get_ports {c0_ddr4_adr[12]}]
set_property PACKAGE_PIN AL15 [get_ports {c0_ddr4_adr[14]}]
set_property PACKAGE_PIN AL19 [get_ports {c0_ddr4_adr[15]}]
set_property PACKAGE_PIN AM19 [get_ports {c0_ddr4_adr[16]}]
set_property PACKAGE_PIN AG15 [get_ports {c0_ddr4_ba[0]}]
set_property PACKAGE_PIN AL18 [get_ports {c0_ddr4_ba[1]}]
set_property PACKAGE_PIN AJ15 [get_ports {c0_ddr4_bg[0]}]
set_property PACKAGE_PIN AE16 [get_ports {c0_ddr4_ck_t[0]}]
set_property PACKAGE_PIN AE15 [get_ports {c0_ddr4_ck_c[0]}]
set_property PACKAGE_PIN AE18 [get_ports {c0_ddr4_cs_n[0]}]
set_property PACKAGE_PIN AJ16 [get_ports {c0_ddr4_cke[0]}]
set_property PACKAGE_PIN AG19 [get_ports {c0_ddr4_odt[0]}]
set_property PACKAGE_PIN AF18 [get_ports c0_ddr4_act_n]
set_property PACKAGE_PIN AG16 [get_ports c0_ddr4_reset_n]
set_property PACKAGE_PIN AL34 [get_ports {c0_ddr4_dq[63]}]
set_property PACKAGE_PIN AN33 [get_ports {c0_ddr4_dq[62]}]
set_property PACKAGE_PIN AM34 [get_ports {c0_ddr4_dq[61]}]
set_property PACKAGE_PIN AN32 [get_ports {c0_ddr4_dq[60]}]
set_property PACKAGE_PIN AM32 [get_ports {c0_ddr4_dq[59]}]
set_property PACKAGE_PIN AP31 [get_ports {c0_ddr4_dq[58]}]
set_property PACKAGE_PIN AP33 [get_ports {c0_ddr4_dq[57]}]
set_property PACKAGE_PIN AN31 [get_ports {c0_ddr4_dq[56]}]
set_property PACKAGE_PIN AK31 [get_ports {c0_ddr4_dq[55]}]
set_property PACKAGE_PIN AJ30 [get_ports {c0_ddr4_dq[54]}]
set_property PACKAGE_PIN AJ34 [get_ports {c0_ddr4_dq[53]}]
set_property PACKAGE_PIN AH32 [get_ports {c0_ddr4_dq[52]}]
set_property PACKAGE_PIN AK32 [get_ports {c0_ddr4_dq[51]}]
set_property PACKAGE_PIN AJ31 [get_ports {c0_ddr4_dq[50]}]
set_property PACKAGE_PIN AH34 [get_ports {c0_ddr4_dq[49]}]
set_property PACKAGE_PIN AH31 [get_ports {c0_ddr4_dq[48]}]
set_property PACKAGE_PIN AN27 [get_ports {c0_ddr4_dq[47]}]
set_property PACKAGE_PIN AL30 [get_ports {c0_ddr4_dq[46]}]
set_property PACKAGE_PIN AN28 [get_ports {c0_ddr4_dq[45]}]
set_property PACKAGE_PIN AL29 [get_ports {c0_ddr4_dq[44]}]
set_property PACKAGE_PIN AP28 [get_ports {c0_ddr4_dq[43]}]
set_property PACKAGE_PIN AM29 [get_ports {c0_ddr4_dq[42]}]
set_property PACKAGE_PIN AP29 [get_ports {c0_ddr4_dq[41]}]
set_property PACKAGE_PIN AM30 [get_ports {c0_ddr4_dq[40]}]
set_property PACKAGE_PIN AH27 [get_ports {c0_ddr4_dq[39]}]
set_property PACKAGE_PIN AK28 [get_ports {c0_ddr4_dq[38]}]
set_property PACKAGE_PIN AH28 [get_ports {c0_ddr4_dq[37]}]
set_property PACKAGE_PIN AK27 [get_ports {c0_ddr4_dq[36]}]
set_property PACKAGE_PIN AJ28 [get_ports {c0_ddr4_dq[35]}]
set_property PACKAGE_PIN AM27 [get_ports {c0_ddr4_dq[34]}]
set_property PACKAGE_PIN AK26 [get_ports {c0_ddr4_dq[33]}]
set_property PACKAGE_PIN AM26 [get_ports {c0_ddr4_dq[32]}]
set_property PACKAGE_PIN AM24 [get_ports {c0_ddr4_dq[31]}]
set_property PACKAGE_PIN AP23 [get_ports {c0_ddr4_dq[30]}]
set_property PACKAGE_PIN AP25 [get_ports {c0_ddr4_dq[29]}]
set_property PACKAGE_PIN AN23 [get_ports {c0_ddr4_dq[28]}]
set_property PACKAGE_PIN AN24 [get_ports {c0_ddr4_dq[27]}]
set_property PACKAGE_PIN AN22 [get_ports {c0_ddr4_dq[26]}]
set_property PACKAGE_PIN AP24 [get_ports {c0_ddr4_dq[25]}]
set_property PACKAGE_PIN AM22 [get_ports {c0_ddr4_dq[24]}]
set_property PACKAGE_PIN AL25 [get_ports {c0_ddr4_dq[23]}]
set_property PACKAGE_PIN AK23 [get_ports {c0_ddr4_dq[22]}]
set_property PACKAGE_PIN AL24 [get_ports {c0_ddr4_dq[21]}]
set_property PACKAGE_PIN AL20 [get_ports {c0_ddr4_dq[20]}]
set_property PACKAGE_PIN AL23 [get_ports {c0_ddr4_dq[19]}]
set_property PACKAGE_PIN AL22 [get_ports {c0_ddr4_dq[18]}]
set_property PACKAGE_PIN AM20 [get_ports {c0_ddr4_dq[17]}]
set_property PACKAGE_PIN AK22 [get_ports {c0_ddr4_dq[16]}]
set_property PACKAGE_PIN AH22 [get_ports {c0_ddr4_dq[15]}]
set_property PACKAGE_PIN AG24 [get_ports {c0_ddr4_dq[14]}]
set_property PACKAGE_PIN AJ24 [get_ports {c0_ddr4_dq[13]}]
set_property PACKAGE_PIN AG25 [get_ports {c0_ddr4_dq[12]}]
set_property PACKAGE_PIN AH23 [get_ports {c0_ddr4_dq[11]}]
set_property PACKAGE_PIN AF23 [get_ports {c0_ddr4_dq[10]}]
set_property PACKAGE_PIN AJ23 [get_ports {c0_ddr4_dq[9]}]
set_property PACKAGE_PIN AF24 [get_ports {c0_ddr4_dq[8]}]
set_property PACKAGE_PIN AE23 [get_ports {c0_ddr4_dq[7]}]
set_property PACKAGE_PIN AE22 [get_ports {c0_ddr4_dq[6]}]
set_property PACKAGE_PIN AG22 [get_ports {c0_ddr4_dq[5]}]
set_property PACKAGE_PIN AD20 [get_ports {c0_ddr4_dq[4]}]
set_property PACKAGE_PIN AG20 [get_ports {c0_ddr4_dq[3]}]
set_property PACKAGE_PIN AF20 [get_ports {c0_ddr4_dq[2]}]
set_property PACKAGE_PIN AF22 [get_ports {c0_ddr4_dq[1]}]
set_property PACKAGE_PIN AE20 [get_ports {c0_ddr4_dq[0]}]
set_property PACKAGE_PIN AG21 [get_ports {c0_ddr4_dqs_t[0]}]
set_property PACKAGE_PIN AH24 [get_ports {c0_ddr4_dqs_t[1]}]
set_property PACKAGE_PIN AJ20 [get_ports {c0_ddr4_dqs_t[2]}]
set_property PACKAGE_PIN AP20 [get_ports {c0_ddr4_dqs_t[3]}]
set_property PACKAGE_PIN AL27 [get_ports {c0_ddr4_dqs_t[4]}]
set_property PACKAGE_PIN AN29 [get_ports {c0_ddr4_dqs_t[5]}]
set_property PACKAGE_PIN AH33 [get_ports {c0_ddr4_dqs_t[6]}]
set_property PACKAGE_PIN AN34 [get_ports {c0_ddr4_dqs_t[7]}]

#set_property PACKAGE_PIN AL32 [get_ports {c0_ddr4_dm_dbi_n[7]}]
#set_property PACKAGE_PIN AJ29 [get_ports {c0_ddr4_dm_dbi_n[6]}]
#set_property PACKAGE_PIN AN26 [get_ports {c0_ddr4_dm_dbi_n[5]}]
#set_property PACKAGE_PIN AH26 [get_ports {c0_ddr4_dm_dbi_n[4]}]
#set_property PACKAGE_PIN AM21 [get_ports {c0_ddr4_dm_dbi_n[3]}]
#set_property PACKAGE_PIN AJ21 [get_ports {c0_ddr4_dm_dbi_n[2]}]
#set_property PACKAGE_PIN AE25 [get_ports {c0_ddr4_dm_dbi_n[1]}]
#set_property PACKAGE_PIN AD21 [get_ports {c0_ddr4_dm_dbi_n[0]}]

set_property PACKAGE_PIN AL32 [get_ports {c0_ddr4_dm_n[7]}]
set_property PACKAGE_PIN AJ29 [get_ports {c0_ddr4_dm_n[6]}]
set_property PACKAGE_PIN AN26 [get_ports {c0_ddr4_dm_n[5]}]
set_property PACKAGE_PIN AH26 [get_ports {c0_ddr4_dm_n[4]}]
set_property PACKAGE_PIN AM21 [get_ports {c0_ddr4_dm_n[3]}]
set_property PACKAGE_PIN AJ21 [get_ports {c0_ddr4_dm_n[2]}]
set_property PACKAGE_PIN AE25 [get_ports {c0_ddr4_dm_n[1]}]
set_property PACKAGE_PIN AD21 [get_ports {c0_ddr4_dm_n[0]}]

set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_odt[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_cke[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_cs_n[0]}]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {c0_ddr4_ck_t[0]}]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {c0_ddr4_ck_c[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[16]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[15]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[14]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[13]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[12]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[11]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[10]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[9]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[8]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[7]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[6]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[5]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[4]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[3]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[2]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[1]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_bg[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_ba[1]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_ba[0]}]
set_property IOSTANDARD LVCMOS12 [get_ports c0_ddr4_reset_n]
set_property IOSTANDARD SSTL12_DCI [get_ports c0_ddr4_act_n]

#set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dm_dbi_n[7]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dm_dbi_n[6]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dm_dbi_n[5]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dm_dbi_n[4]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dm_dbi_n[3]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dm_dbi_n[2]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dm_dbi_n[1]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dm_dbi_n[0]}]

set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dm_n[7]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dm_n[6]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dm_n[5]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dm_n[4]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dm_n[3]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dm_n[2]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dm_n[1]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dm_n[0]}]

set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[63]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[62]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[61]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[60]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[59]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[58]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[57]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[56]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[55]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[54]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[53]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[52]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[51]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[50]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[49]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[48]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[47]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[46]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[45]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[44]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[43]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[42]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[41]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[40]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[39]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[38]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[37]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[36]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[35]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[34]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[33]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[32]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[31]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[30]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[29]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[28]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[27]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[26]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[25]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[24]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[23]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[22]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[21]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[20]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[19]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[18]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[17]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[16]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[15]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[14]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[13]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[12]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[11]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[10]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[9]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[8]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[7]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[6]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[5]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[4]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[3]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[2]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[1]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[0]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_t[7]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_c[7]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_t[6]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_c[6]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_t[5]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_c[5]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_t[4]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_c[4]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_t[3]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_c[3]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_t[2]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_c[2]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_t[1]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_c[1]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_t[0]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_c[0]}]